# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-15 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perimeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('theme', models.CharField(choices=[('IR', 'Infrastructure et r\xe9seau'), ('SP', 'S\xe9curisation des plateformes'), ('AC', 'Authentification et chiffrement'), ('GS', 'Gestion des sessions'), ('CA', 'Contr\xf4le des autorisations'), ('TP', 'Traitement des param\xe8tres'), ('CL', 'Conformit\xe9 l\xe9gale')], max_length=2)),
                ('state', models.CharField(choices=[('O', 'Open'), ('R', 'Retry'), ('C', 'Closed')], default='O', max_length=2)),
                ('porteur', models.CharField(choices=[('A', 'Architect'), ('D', 'Developer'), ('E', 'Exploitant')], max_length=2)),
                ('recommendation', models.TextField()),
                ('perimeter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perimeter', to='frontend.Perimeter')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
