# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20180515_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='perimeter',
            name='major',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perimeter',
            name='minor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perimeter',
            name='moderate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='perimeter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='frontend.Perimeter'),
        ),
    ]
