# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20180527_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='perimeter',
            name='color',
            field=models.CharField(default='orange', max_length=200),
            preserve_default=False,
        ),
    ]
