# Generated by Django 2.2.5 on 2019-09-06 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20190906_0847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perimeter',
            options={'permissions': (('change_status', 'Change vulnerability status'),)},
        ),
    ]
