# Generated by Django 2.2.5 on 2019-09-06 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20190906_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('file', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='accountability',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='availability',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='complexity',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='confidentiality',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='integrity',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='interaction',
            field=models.CharField(choices=[('N', 'None'), ('Y', 'Yes')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='mode_operatoire',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='privileges',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='media',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='frontend.Video'),
        ),
    ]
