# Generated by Django 2.2.5 on 2019-09-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_vulnerability_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='perimeter',
            name='spent_budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perimeter',
            name='total_budget',
            field=models.IntegerField(default=0),
        ),
    ]
