# Generated by Django 2.2.5 on 2019-09-06 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_video_vulnerability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='urls',
            new_name='url',
        ),
    ]
