# Generated by Django 2.2.5 on 2019-09-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_auto_20190906_1556'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='Account',
        ),
    ]
