# Generated by Django 2.2.5 on 2019-09-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_auto_20190906_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerability',
            name='note',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
