# Generated by Django 2.2.5 on 2019-09-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0020_auto_20190923_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='note',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
