# Generated by Django 2.2.5 on 2019-09-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0022_vulnerability_criticality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='criticality',
            field=models.CharField(choices=[('L', 'Minor'), ('M', 'Moderate'), ('H', 'Major')], default='L', max_length=1),
        ),
    ]
