# Generated by Django 2.2.5 on 2019-09-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0023_auto_20190924_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='theme',
            field=models.CharField(choices=[('Infrastructure et réseau', 'Infrastructure et réseau'), ('SP', 'Sécurisation des plateformes'), ('AC', 'Authentification et chiffrement'), ('GS', 'Gestion des sessions'), ('CA', 'Contrôle des autorisations'), ('TP', 'Traitement des paramètres'), ('CL', 'Conformité légale')], max_length=2),
        ),
    ]
