# Generated by Django 2.2.5 on 2019-09-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0024_auto_20190925_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='theme',
            field=models.CharField(choices=[('Infrastructure et réseau', 'Infrastructure et réseau'), ('SP', 'Sécurisation des plateformes'), ('AC', 'Authentification et chiffrement'), ('GS', 'Gestion des sessions'), ('Contrôle des autorisations', 'Contrôle des autorisations'), ('TP', 'Traitement des paramètres'), ('CL', 'Conformité légale')], max_length=2),
        ),
    ]
