# Generated by Django 2.2.5 on 2019-09-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0026_auto_20190925_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='theme',
            field=models.CharField(choices=[('Infrastructure et réseau', 'Infrastructure et réseau'), ('Sécurisation des plateformes', 'Sécurisation des plateformes'), ('Authentification et chiffrement', 'Authentification et chiffrement'), ('Gestion des sessions', 'Gestion des sessions'), ('Contrôle des autorisations', 'Contrôle des autorisations'), ('Traitement des paramètres', 'Traitement des paramètres'), ('Conformité légale', 'Conformité légale')], max_length=40),
        ),
    ]
