# Generated by Django 2.2.5 on 2019-09-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0027_auto_20190925_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='note',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
