# Generated by Django 2.2.5 on 2019-09-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0029_auto_20190925_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='vector',
            field=models.DecimalField(choices=[(0.2, 'Physical'), (0.55, 'Local'), (0.62, 'Adjacent Network'), (0.85, 'Network')], decimal_places=2, max_digits=3),
        ),
    ]
