# Generated by Django 2.2.5 on 2019-09-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0030_auto_20190925_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='vector',
            field=models.DecimalField(choices=[(2, 'Physical'), (55, 'Local'), (62, 'Adjacent Network'), (85, 'Network')], decimal_places=2, max_digits=3),
        ),
    ]
