# Generated by Django 2.2.5 on 2019-09-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0031_auto_20190925_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='vector',
            field=models.CharField(choices=[('0.2', 'Physical'), ('0.55', 'Local'), ('0.62', 'Adjacent Network'), ('0.85', 'Network')], max_length=5),
        ),
    ]
