# Generated by Django 2.2.5 on 2019-09-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0032_auto_20190925_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='availability',
            field=models.CharField(choices=[('0', 'None'), ('0.22', 'Low'), ('0.56', 'High')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='complexity',
            field=models.CharField(choices=[('0.77', 'Low'), ('0.44', 'High')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='confidentiality',
            field=models.CharField(choices=[('0', 'None'), ('0.22', 'Low'), ('0.56', 'High')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='integrity',
            field=models.CharField(choices=[('0', 'None'), ('0.22', 'Low'), ('0.56', 'High')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='interaction',
            field=models.CharField(choices=[('0.85', 'None'), ('0.62', 'Required')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='privileges',
            field=models.CharField(choices=[('0.85', 'None'), ('0.62', 'Low'), ('0.27', 'High')], default='N', max_length=1),
        ),
    ]
